version: "3.8"
services:
  todo_app:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - ./:/app
    container_name: todo_app
    ports:
      - 8080:8080
      - 5051:5051
